### ISSUE TITLE
WID is removed in AXI4

### ISSUE THREAD

**Issue by drom** [Minres/SystemC-Components#26]
When using the AXI4 pin adapter: "axi::pin::axi4_target" I have to bind the "w_id" port.

https://github.com/Minres/SystemC-Components/blob/0e182dd20e5f483f5ffd6341f55a29931a957561/src/bus_interfaces/axi/signal_if.h#L165

"WID" port was removed in the AXI4 specification. ARM IHI 0022E ID033013 As described below.

![image](https://user-images.githubusercontent.com/511872/165548012-3b0eeec8-69ae-40bc-a0bf-0de47b9ac5da.png)
![image](https://user-images.githubusercontent.com/511872/165548114-438d0ea1-fb59-40e0-80f8-9ccf1b250d8b.png)
![image](https://user-images.githubusercontent.com/511872/165548373-20a359fd-7535-4139-9f24-64abc3019b0d.png)
![image](https://user-images.githubusercontent.com/511872/165548537-8f71591a-91dc-43e7-aadd-06ffc7586849.png)
![image](https://user-images.githubusercontent.com/511872/165548771-292cf3ad-c0ed-4626-9bc4-93f7392b248b.png)

**Comment by eyck** [comment]
Intertestingly this statement cannot be found in the IHI0022H revision of the AMBA spec...

**Comment by eyck** [comment]
The WID port is now optional. It was not used in the target anyways
