### ISSUE TITLE
ar_ready incorrect timing diagram

### ISSUE THREAD

**Issue by mslijepc** [Minres/SystemC-Components#34]
In some cases, it appears incorrect timing diagram of `ar_ready` signal (half-cycle asserted signal).

![image](https://user-images.githubusercontent.com/77167949/184898178-196a3924-47e8-4bd0-806c-6c8ec9f893f1.png)

**Comment by eyck** [comment]
This is valid according to the AXI spec as it is sampled on the rising edge of the clock. And the AXI spec states in section 'A3.2.1 Handshake process':
> When VALID is asserted, it must remain asserted until the handshake occurs, at a rising clock edge when VALID 
and READY are both asserted.
I agree this is not nice but correct

**Comment by mslijepc** [comment]
How many transactions then in this case should be (i.e. how many valid addresses)?

**Comment by eyck** [comment]
The picture shows 5 transactions, 1 to the left of the cursor and 4 to the right. Whenever the condition ar_valid==1 && ar_ready==1 is tru right before the clock rises.
