### ISSUE TITLE
r_valid and burst request duration issue

### ISSUE THREAD

**Issue by mslijepc** [Minres/SystemC-Components#36]
Hi Eyck, 

in AXI4 protocol, if there is e.g. a burst read transaction of size 2, how many cycles should it last? From the moment it puts first `r_valid` to `true` until it asserts `r_last` ? 

![image](https://user-images.githubusercontent.com/77167949/188834474-3b94b705-1ed7-43b1-8f72-cb72d1112f22.png)

From this waveform, I can see it lasting 3 cycles, but shouldn't it last 2 cycles?

We can see that `axi4_target` is asserting `r_valid` for 1 cycle, w\o considering whether there is a new data, is that 1 cycle meant to always occur and therefore the burst of size 2 should last minimum 3 cycles?
https://github.com/Minres/SystemC-Components/blob/e2dea44610e04bc4f7189ce9aacc424f4d15e011/src/bus_interfaces/axi/pin/axi4_target.h#L296

**Comment by eyck** [comment]
The target aserts r_valid signaling that this is the first beat (incl. data) of the 2-beat burst. This is immedaitely acknoledged by the intitiator since r_ready is asserted. So the first beat enda after 1 clock cycle. Then the target inserts 1 clock delay and asserts in the 3rd cycle r_valid and r_last thus signalling that this is the second and final beat. This is also immediately acknowledged by the initiator since ready is asserted. So at 27300ns the response is finished after 2 1-cycle beats and 1 cycle intra-beat delay.

**Comment by mslijepc** [comment]
I am using `axi::pe::simple_target`. 

> it seems your target is configured to insert 1 cycle delay between END_PARTIAL_RESP and BEGIN_RESP.

Can we "configure" / affect on this, shouldn't they arrive in w/o delay?

Even if `END_PARTIAL_RESP` and `BEGIN_RESP` would arrive in 2 consecutive cycles, since in `rresp_t` we always wait for 1 cycle, ` cycle intra-beat delay will always happen?

**Comment by eyck** [comment]
Yes, this can be configured at the pe of the simple_target. There is a sc_attribute called [rd_data_beat_delay](https://github.com/Arteris-IP/tlm2-interfaces/blob/e1fd390f34235755071a83d812df7fc2b4c2ebd4/axi/pe/axi_target_pe.h#L75).
If you look at the [axi pin example](https://github.com/Minres/SystemC-Components/tree/main/examples/axi4_tlm-pin-tlm) there are no cycles between the read responses.

**Comment by eyck** [comment]
Can this be closed?

**Comment by mslijepc** [comment]
I was just checking, `rd_data_beat_delay` is `0`. I will debug it tomorrow to see the root cause

**Comment by eyck** [comment]
You might also have a look at https://git.minres.com/SystemC/SystemC-Components-Test/src/branch/develop/tests/axi4_pin_level which shows:
![grafik](https://user-images.githubusercontent.com/437271/194396785-57d10169-3a46-402d-83c6-59213b0ede09.png)

**Comment by eyck** [comment]
Hi Mladen, what about this issue? Did you solve it? Can it be closed?
