### ISSUE TITLE
Q: Build instructions help

### ISSUE THREAD

**Issue by mslijepc** [Minres/SystemC-Components#49]
I am trying to compile, and have some issues with `conan`. 
 
If I install `conan`, it installs version2, so I get issues with `conanfile.txt` (`conan2` is using different syntax)
```
ERROR: Error while parsing [options] in conanfile.txt
Options should be specified as 'pkg/*:option=value'
```

On the other hand, if I install version `1.59`, as recommended in the `README.md` I get issues with compiler version
```
ERROR: Invalid setting '13' is not a valid 'settings.compiler.version' value.
Possible values are ['4.1', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2', '5.3', '5.4', '5.5', '6', '6.1', '6.2', '6.3', '6.4', '6.5', '7', '7.1', '7.2', '7.3', '7.4', '7.5', '8', '8.1', '8.2', '8.3', '8.4', '8.5', '9', '9.1', '9.2', '9.3', '9.4', '9.5', '10', '10.1', '10.2', '10.3', '10.4', '11', '11.1', '11.2', '11.3', '12', '12.1', '12.2']
```

How did you solve this issue?
P.s. I am using Opensuse OS

**Comment by eyck** [comment]
All systems where we used SCC have older compilers. You might try to use version 1.61 of conan:
```pip install 'conan<2.0' ```

**Comment by eyck** [comment]
All systems where we used SCC have older compilers. You might try to use version 1.61 of conan:
```pip install 'conan<2.0' ```
