### ISSUE TITLE
Which SystemC version?

### ISSUE THREAD

**Issue by cnjsdfcy** [Minres/SystemC-Components#54]
Hi,

Thanks for the library.

I'm compiling SCC with systemc-2.3.1 which is built using g++-11.4.0 with -std=C++11, it comes out with many warnings and one error:
![image](https://github.com/Minres/SystemC-Components/assets/5670527/2889ea93-08a8-4bc2-bdbe-6e399be4bef7)

So which systemc version do you recommend?

Thanks,
Yu

**Comment by eyck** [comment]
Actually I recommend 2.3.4. 2..3.3 is also possible. Actually it should build without warnings, but we do not test against 2.3.1 as this release is more than 9 years old and even all major vendors support 2.3.3 in their tools.
To be future proof I'd recommend to also switch to C++17, Version 3.0 of SystemC (released last year) has this as a minimum requirement.
