### ISSUE TITLE
build fails with c++std>11 

### ISSUE THREAD

**Issue by JoGei** [Minres/SystemC-Components#7]
Hello,

The README specifies a c++11. I was wondering if SCC could be used with c++std>11, too, but noticed that the build fails because of a missing include in [incl/scc/report.h](https://github.com/Minres/SystemC-Components/blob/5766c453820b237578b6c535bf9f63fc995c3170/incl/scc/report.h#L26)

Here is the log of a c++17 build with GCC 10: [scc_buildlog.txt](https://github.com/Minres/SystemC-Components/files/5643257/scc_buildlog.txt)

The fix is to include `<cstring>` in the header to make `strcmp` visible again. Here is the patch: [0001-insert-cstring-include-for-c-11.patch.txt](https://github.com/Minres/SystemC-Components/files/5643294/0001-insert-cstring-include-for-c-11.patch.txt)
The include should not interfere with c++11.

**Comment by eyck** [comment]
It shoudl be possible to use SCC with c++14 but this has not been tested yet. THX for reporting this
