### ISSUE TITLE
the example doc

### ISSUE THREAD

**Issue by hanm2019** [Minres/SystemC-Components#8]
Hi, I am interested in your project, and I am looking for a new way to record the TLM trans instead of the logfile, I think you project may be a good solution, but i am confuse with the simple README.md, and don't know how to use in my systemC project, it would be better if there are some example  : )

**Comment by eyck** [comment]
THX for the feedback. Indeed we are already working on it.

**Comment by eyck** [comment]
The example directory containt now mostyl bus oriented exampls which also demonstrate the use of configuguration and logging as well as transaction recording.

**Comment by hanm2019** [comment]
thanks
